namespace PushToDb.Model;

/// <summary>
/// A cover image. The loader creates the artwork row pointing at the scanned source
/// asset; resized variants are generated by a later pass, not at load time.
/// </summary>
public class Artwork
{
    public Guid Id { get; set; }

    public Guid SourceAssetId { get; set; }

    public List<string> Colors { get; set; } = [];
}
